name: material_color_json
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.1

# Add regular dependencies here.
# dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  material_color_utilities: 
